In [1]:
import torch
# The train split of client 1
train_data_client1 = torch.load('./data/CIKM22Competition/4/val.pt')
# Check the first sample
print(train_data_client1[0])
# Check the label of the first sample
print(len(train_data_client1))
# Check the index of the first sample as ${sample_id}
print(train_data_client1[0].data_index)

Data(x=[16, 7], edge_index=[2, 34], edge_attr=[34, 4], y=[1, 1], data_index=0)
34
0


In [2]:
train_data_client1[0].edge_index

tensor([[ 0,  0,  1,  2,  2,  2,  3,  3,  3,  4,  4,  5,  6,  6,  6,  7,  7,  8,
          8,  9, 10, 10, 10, 11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 15],
        [ 2,  8, 10,  0, 12, 13,  6, 14, 10,  7, 13, 10, 13, 11,  3, 14,  4,  0,
         11, 12,  3,  1,  5,  8,  6,  2,  9, 15,  4,  2,  6,  7,  3, 12]])

In [3]:
from federatedscope.contrib.data.cikm_cup import CIKMCUPDataset
from torch_geometric.data import InMemoryDataset

t=CIKMCUPDataset('./data/CIKM22Competition/1/')

Processing...
Done!


In [4]:
from torch_geometric import data#.summary import Summary

In [5]:
train_data_client1[0].keys

['edge_attr', 'x', 'edge_index', 'y', 'data_index']

In [6]:
ys = [train_data_client1[i].y for i in range(len(train_data_client1)-1)]

In [7]:
sum(ys)

tensor([[22]])

In [8]:
sum(ys) / len(ys)

tensor([[0.6667]])

In [9]:
1- sum(ys) / len(ys)

tensor([[0.3333]])

1: 1249
2: 181
3: 2219
4: 101
5: 188
6: 1101
7: 2228
8: 777
9: 134706
10: 109392
11: 2268
12: 608
13: 70648

1: 0
2: 0
3: 0
4:1
5:0
6:1
7:0

In [10]:
import numpy as np

In [ ]:
13

In [1]:
!python federatedscope/main.py --cfg federatedscope/gfl/baseline/laplacian_gine_on_cikmcup.yaml --client_cfg federatedscope/gfl/baseline/laplacian_gine_on_cikmcup_per_client.yaml federate.total_round_num 5000

/home/michael/Projects/CKIM_other/CIKM22_FL_Competition/venv/lib/python3.9/site-packages/torch_geometric/graphgym/imports.py:14: UserWarning: Please install 'pytorch_lightning' for using the GraphGym experiment manager via 'pip install pytorch_lightning'
  warnings.warn("Please install 'pytorch_lightning' for using the GraphGym "
/home/michael/Projects/CKIM_other/CIKM22_FL_Competition/venv/lib/python3.9/site-packages/torch_geometric/graphgym/logger.py:23: UserWarning: Please install 'pytorch_lightning' for using the GraphGym experiment manager via 'pip install pytorch_lightning'
  warnings.warn("Please install 'pytorch_lightning' for using the GraphGym "
2022-10-23 13:09:09,928 (trainer_builder:11)WARNING: No module named 'federatedscope.contrib.optimizer' in `federatedscope.contrib.trainer`, some modules are not available.
2022-10-23 13:09:09,939 (utils:129)INFO: the current machine is at 127.0.1.1
2022-10-23 13:09:09,939 (utils:131)INFO: the current dir is /home/michael/Projects/CKIM

In [11]:
 client 5

SyntaxError: invalid syntax (2568309106.py, line 1)

In [2]:
!python federatedscope/main.py --cfg federatedscope/gfl/baseline/laplacian_gine_on_cikmcup.yaml --client_ federatedscope/gfl/baseline/laplacian_gine_on_cikmcup_per_client.yaml federate.total_round_num 50

2022-10-23 09:38:06,852 (trainer_builder:11)WARNING: No module named 'federatedscope.contrib.optimizer' in `federatedscope.contrib.trainer`, some modules are not available.
2022-10-23 09:38:06,864 (utils:129)INFO: the current machine is at 127.0.1.1
2022-10-23 09:38:06,864 (utils:131)INFO: the current dir is /home/michael/Projects/CKIM_Competition
2022-10-23 09:38:06,864 (utils:132)INFO: the output dir is exp/FedAvg_gin_on_cikmcup_lr0.1_lstep10_/sub_exp_20221023093806
2022-10-23 09:38:06,945 (cikm_cup:57)INFO: Loading CIKMCUP data from /home/michael/Projects/CKIM_Competition/data/CIKM22Competition.
2022-10-23 09:38:06,945 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #1.
2022-10-23 09:38:07,285 (config:261)INFO: the used configs are: 
asyn:
  min_received_num: 1
  min_received_rate: -1.0
  timeout: 0
  use: True
attack:
  alpha_TV: 0.001
  alpha_prop_loss: 0
  attack_method: 
  attacker_id: -1
  classifier_PIA: randomforest
  info_diff_type: l2
  inject_round: 0
  max_ite: 400
  r