In [98]:
import torch

In [141]:
a = torch.Tensor([[1,5,5]])
b = torch.Tensor([[5,5,5]])

In [142]:
target = torch.ones(a.size(0))
target = target -2

In [143]:
cos_emb = torch.nn.CosineEmbeddingLoss()

In [144]:
cos_emb(a,b, target)

tensor(0.8893)

In [123]:
target

tensor([-1.])

In [124]:
a

tensor([[0., 0., 0.]])

In [105]:
b

tensor([[1., 1., 2.]])