In [2]:
import torch

In [93]:
a = torch.Tensor([[1,1], [2,2], [3,3]])
b = torch.Tensor([[1,1], [2,2], [3,3]])

In [94]:
def forward(input1, input2):
    batch_size = input1.size(0)
    input1 = input1.view(batch_size, -1)
    input2 = input2.view(batch_size, -1)
    print(input1)
    input1_l2_norm = torch.norm(input1, p=2, dim=1, keepdim=True).detach()
    print(input1_l2_norm)
    input1_l2 = input1.div(input1_l2_norm.expand_as(input1) + 1e-6)
    print(input1_l2)

    input2_l2_norm = torch.norm(input2, p=2, dim=1, keepdim=True).detach()
    input2_l2 = input2.div(input2_l2_norm.expand_as(input2) + 1e-6)
    print(input2_l2)
    diff_loss = torch.mean((input1.t().mm(input2)).pow(2))

    return diff_loss

In [95]:
forward(a,b)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.]])
tensor([[1.4142],
        [2.8284],
        [4.2426]])
tensor([[0.7071, 0.7071],
        [0.7071, 0.7071],
        [0.7071, 0.7071]])
tensor([[0.7071, 0.7071],
        [0.7071, 0.7071],
        [0.7071, 0.7071]])


tensor(196.)

In [2]:
rho_data

array([[-0.49078941, -0.2923246 ],
       [-0.79202389, -0.48998526],
       [ 0.31017057,  0.53817494],
       [-1.06978377, -0.75609477],
       [-1.82777587, -1.24171745],
       [-2.68973676, -2.34460155],
       [-0.39912216,  0.42128307],
       [ 0.384915  ,  0.50746536],
       [ 1.74402231,  1.85666967],
       [ 0.95182507,  1.0636386 ],
       [ 0.14752857, -0.20643161],
       [-1.50407367, -2.19086867],
       [ 0.87868791,  0.59247856],
       [-0.49972743, -0.66337643],
       [-0.41090189, -0.24924447],
       [ 1.20084434,  1.15697343],
       [-0.04158464, -0.14451038],
       [ 0.62609941,  0.093792  ],
       [ 0.66380265,  0.220834  ],
       [ 0.37974101,  0.35507449],
       [ 0.62579096,  0.74871706],
       [ 2.5592614 ,  1.92038387],
       [ 0.08961008, -0.46331465],
       [-0.12221028, -0.73169423],
       [ 0.08891445,  0.03529864],
       [ 0.38612717,  0.05365423],
       [ 0.67756775,  0.77653046],
       [ 1.01595174,  1.20231207],
       [-0.23252599,

In [3]:
import torch

In [4]:
a = torch.normal(0,3, size=(64,512))

In [5]:
a

tensor([[-0.0906, -6.2236, -2.2263,  ..., -0.6967,  0.1048,  0.9349],
        [-1.4139, -2.9358,  1.1636,  ..., -3.9133, -1.6324,  0.8730],
        [-3.0204,  2.9446, -4.8308,  ..., -4.2680, -0.1978,  0.2965],
        ...,
        [ 3.5705, -0.9740, -3.8369,  ..., -0.5043,  0.4298,  2.5196],
        [-1.4540, -0.3725, -2.7886,  ..., -0.0189,  2.8597, -1.9920],
        [ 2.1273, -0.5393, -3.7211,  ...,  1.9747, -3.0517, -2.3277]])

In [6]:
x = np.random.multivariate_normal( mean=[0,0],
                                  cov=[[1,0.8],[0.8,1]],
                                 size = (64,1))

In [7]:
x_1 = x[:,:,0:1]

In [8]:
x_1

array([[[ 0.67046532]],

       [[ 0.34616545]],

       [[ 0.38991884]],

       [[-1.77612658]],

       [[-0.14414848]],

       [[-1.20774585]],

       [[ 1.29355016]],

       [[-0.8635706 ]],

       [[ 1.37558559]],

       [[ 0.2731224 ]],

       [[ 0.07749822]],

       [[ 1.88390253]],

       [[ 1.73452898]],

       [[ 0.38846777]],

       [[ 0.50475763]],

       [[-1.67825078]],

       [[-0.30424783]],

       [[-0.45457923]],

       [[-0.97042346]],

       [[-0.25988772]],

       [[-0.47592474]],

       [[-0.11772016]],

       [[ 0.41248567]],

       [[ 1.41618271]],

       [[-1.44528921]],

       [[ 1.16208921]],

       [[ 0.92868338]],

       [[ 0.71562145]],

       [[-0.62674905]],

       [[ 0.879626  ]],

       [[-1.5552406 ]],

       [[ 0.0338778 ]],

       [[ 1.29077357]],

       [[-1.09242223]],

       [[ 1.57843911]],

       [[-0.7437657 ]],

       [[ 0.4314983 ]],

       [[-0.13520804]],

       [[ 1.14522257]],

       [[-0.49581753]],



In [9]:
x_2 = x[:,:,1]

In [10]:
import matplotlib.pyplot as plt
plt.plot(x[1,:,:])
#plt.plot(x_2[0,:])

In [11]:
x[1,:,:]

array([[ 0.34616545, -0.04239312]])

In [12]:
x[1,:,:]

array([[ 0.34616545, -0.04239312]])

In [13]:
x[1,:,:][0]

array([ 0.34616545, -0.04239312])

In [14]:
x_1.shape

(64, 1, 1)

In [1]:
import numpy as np
cov_matrix = np.array([[1,0.9], [0.9,1]])
-0.5 * np.log(np.linalg.det(cov_matrix))

0.8303656034108255